### ISSUE TITLE
How to Convert CIDR to IP Range ?

### ISSUE THREAD

**Issue by bwenquan** [seancfoley/ipaddress-go#3]
Hi.

I want to convert CIDR to IP Range, but I can't find any method like `GetAllAddress()`.

Input:
```
192.168.1.0/24
```

OutPut:
```
192.168.1.1
192.168.1.2
192.168.1.3
......
192.168.1.253
192.168.1.254
```

Thanks for your help.

**Comment by seancfoley** [comment]
Hello,


This code will do it.  
```go
// WithoutPrefixLen drops the /24 
subnet := ipaddr.NewIPAddressString("192.168.1.0/24").GetAddress().WithoutPrefixLen()   
iterator := subnet.Iterator()
highest := subnet.GetUpper() // highest is 192.168.1.255
next := iterator.Next() // skips the lowest address, 192.168.1.0
for next = iterator.Next(); !next.Equal(highest); next = iterator.Next() { // skips 192.168.1.255
//for next = iterator.Next(); next != nil ; next = iterator.Next() { // this would include 192.168.1.255
	fmt.Println(next)
}
```
There are other variations, you could get the subnet size with GetCount and then just count to the end.

You can follow [this example](https://github.com/seancfoley/ipaddress-go/wiki/Code-Examples-3:-Subnetting-and-Other-Subnet-Operations#iterate-through-subnet) for variations on it.
