### ISSUE TITLE
ipaddr v1.5.2 bintree error

### ISSUE THREAD

**Issue by mrjosh** [seancfoley/ipaddress-go#4]
Hi there, 

I got this error after upgrading to version v1.5.1
GoVersion: 1.19

```
/Users/josh/.go/pkg/mod/github.com/seancfoley/bintree@v1.2.1/tree/trienode.go:542:25: internal compiler error: method GetBitCount on *uint8 not found
```

**Comment by seancfoley** [comment]
It seems odd, since there is no call to GetBitCount at that [location](https://github.com/seancfoley/bintree/blob/v1.2.1/tree/trienode.go#L542).  I have not identified or reproduced such an error so far.  Are you compiling your fork of ipaddress-go, and are there code changes in it?

**Comment by seancfoley** [comment]
This was likely a compile-error resulting from code changes in the ipaddress-go repo that end up breaking the generic type constraints required by bintree - so not a bug.
