### ISSUE TITLE
internal compile rerror

### ISSUE THREAD

**Issue by gakkilover** [seancfoley/ipaddress-go#9]
The error is: vendor\github.com\seancfoley\bintree\tree\trienode.go:542:25: internal compiler error: method GetBitCount on *uint8 not found
when i run golang project

**Comment by seancfoley** [comment]
This looks very similar to https://github.com/seancfoley/ipaddress-go/issues/4 which I could not reproduce.

It looks a lot like https://github.com/golang/go/issues/54225

**Comment by seancfoley** [comment]
What version of go are you using?

**Comment by seancfoley** [comment]
No response from the bug opener, so closing.  

This looks like https://github.com/golang/go/issues/54225, a regression with earlier versions of go version 1.19 that has since been fixed in later versions.
